#Test with: http://editor.swagger.io/

swagger: '2.0'
info:
  version: 1.0.0
  title: Matches Microservice for Picaditos
  description: Elixir + PostgreSQL
  license:
    name: Software Architecture 2018-II
host: 192.168.99.101:4004
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /matches:
    post:
      summary: Creates a new match
      operationId: createMatch
      parameters:
        - name: match
          in: body
          required: true
          description: Match Object
          schema:
            $ref: '#/definitions/MatchInput'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/SingleMatch'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/GenericError'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/GenericError'
        '422':
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/FieldError'
    get:
      summary: Returns all matches
      operationId: getAllMatches
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/MatchesList'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/GenericError'

  /matches/{id}:
    get:
      summary: Returns a match with the given id
      operationId: getMatchbyId
      parameters:
        - name: id
          in: path
          description: The id of the match to be returned
          required: true
          type: integer
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/SingleMatch'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/GenericError'
        '400':
            description: Bad Request
            schema:
              $ref: '#/definitions/GenericError'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/GenericError'

    put:
      summary: Updates a match with the given id
      operationId: updateMatch
      parameters:
        - name: id
          in: path
          description: The id of the match to be updated
          required: true
          type: integer
        - name: match
          in: body
          required: true
          description: Match Object
          schema:
            $ref: '#/definitions/MatchInput'
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/SingleMatch'  
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/GenericError'
        '400':
            description: Bad Request
            schema:
              $ref: '#/definitions/GenericError'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/GenericError'
        '422':
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/FieldError'

    delete:
      summary: Deletes a match with the given id
      operationId: deleteMatch
      parameters:
        - name: id
          in: path
          description: The id of the match to be deleted
          required: true
          type: integer
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/GenericError'
        '400':
            description: Bad Request
            schema:
              $ref: '#/definitions/GenericError'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/GenericError'
definitions:

  Match:
    type: object
    properties:
      id:
        type: integer
      court_id:
        type: integer
      team_home_id:
        type: integer
      team_away_id:
        type: integer
      date:
        type: string
      played:
        type: boolean
      score_home:
        type: integer
      score_away:
        type: integer

  MatchInput:
    type: object
    properties:
      match:
        type: object
        properties:
          court_id:
            type: integer
          team_home_id:
            type: integer
          team_away_id:
            type: integer
          date:
            type: string
          played:
            type: boolean
          score_home:
            type: integer
          score_away:
            type: integer

  MatchesList:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/Match'
          
  SingleMatch:
    type: object
    properties:
      data:
        $ref: '#/definitions/Match'

# Errors
  GenericError:
    type: object
    properties:
      error:
        type: object
        properties:
          detail:
            type: string
  FieldError:
    type: object
    properties:
      error:
        type: object
        properties:
          field:
            type: array
            items:
              type: string
