version: '2.1'

services:
  matches-ms:
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: matchService_dev
      PGPORT: 5432
      PGHOST: matches-db
    ports:
      - "4004:4004"
    depends_on:
      - matches-db
  matches-db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
