version: '2.1'

services:
  partidos-ms:
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: partidoService_dev
      PGPORT: 5432
      PGHOST: partidos-db
    ports:
      - "4000:4000"
    depends_on:
      - partidos-db
  partidos-db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
